### ISSUE TITLE
The content of the columns from stacked user lists is not aligned

### ISSUE THREAD

**Issue by AndreeaChi** [xwikisas/xwiki-pro-macros#113]
Steps to reproduce:
1. Install Pro Macros 1.7
2. Create 2 users and complete the email, company, phone, address with content of different length
3. On a page, add a line of text and below it the user list macro with the properties: avatar,username,email,company,phone,address and one of the created users in the second field.
4. Add a second line of text and below it another user list macro with the same properties as above and the second created user.

Result:
<img width="563" alt="test-support-stacked-multiple-user-lists" src="https://user-images.githubusercontent.com/36840106/220363649-f3fae679-bf33-49fe-b28b-dd88877e8a74.png">

Wanted result would involve that the content is aligned even if the content in each cell differs.

**Comment by AndreeaChi** [comment]
Once there are two users added in the user list, the content of the columns are automatically aligned within each list, providing a cleaner layout altogether:

<img width="539" alt="image" src="https://user-images.githubusercontent.com/36840106/220368030-e1c99945-7b4a-4128-a327-a40c79702f02.png">

**Comment by raphj** [comment]
The CSS `table-layout: fixed` rule might help, though it comes with other issues. I believe one have to pick their poison in such situation, there's no ideal solution I think.

https://developer.mozilla.org/en-US/docs/Web/CSS/table-layout

See also a potential problem related to fixed table layouts,
 with its solution https://stackoverflow.com/questions/17699324/fixed-table-layout-overflow-to-the-side

**Comment by slauriere** [comment]
Thank you @raphj! Also adding here your suggestion for the record, I will consider it:

> I'm not totally sure this "fix" should be applied unconditionally, maybe a "fixed layout" macro parameter should be provided, or something like this.
