### ISSUE TITLE
Inline rendering converted into block

### ISSUE THREAD

**Issue by petrenkonikita112263** [xwikisas/xwiki-pro-macros#126]
**Prerequisites**
XWiki 14.10.5

**Step to reproduce**

1. Install Pro Macro v.1.7
2. Obtain trial license
3. Go to Sandbox or any test page and place this code
```
aaaa {{status title="Texte1" colour="Grey"/}} bbbb {{status title="Texte2" colour="Grey"/}} cccc
```
4. Save it

Result 
![image](https://user-images.githubusercontent.com/56109799/236439200-3c291ef7-53c9-4166-88ea-85848c54d945.png)

5. Upgrade Pro Macro up to v1.8.1 (same if upgrade up to 1.8 or 1.7.1)
During this process, observe the installation log and see this line
`Can't find any existing component with class [com.xwiki.macros.userlist.internal.macro.GroupReferenceListConverter]. Ignoring it.`
6. Refresh page that was edited on step 3

Result
![image](https://user-images.githubusercontent.com/56109799/236439501-eb686350-c6ed-4866-bd03-7565b9f2d41b.png)

_Note:_ if you observer the code again it will be transformed into
```
aaaa {{status title="Texte1" colour="Grey"/}}

(% class="greyStatus statusBox" title="Texte1" %)Texte1

bbbb {{status title="Texte2" colour="Grey"/}}

(% class="greyStatus statusBox" title="Texte2" %)Texte2

cccc
```
 

**Expected Result**
The update has no effect on Status macro. The layout is still the same as it was after step 4.

**Comment by oanalavinia** [comment]
Caused by https://github.com/xwikisas/xwiki-pro-macros/issues/110
