### ISSUE TITLE
File isn't shown when it contains a comma in the title

### ISSUE THREAD

**Issue by ane-gabriela** [xwikisas/xwiki-pro-macros#136]
Preconditions:
The office server needs to be configured and connected to the XWiki instance. Add attachments to the page used (doc, docx, xls, xlsx, ppt, pptx, and pdf) that have special characters in the title.

Steps to reproduce:

1. Edit a page
2. Click on Insert > Other macros 
3. Search and select View Files
4. In the "att--filename" text box add the name of a file from the attachments section, including the file extension eg. "Te$t with #special + ch@rs - test. It's ^a test! Test 1 = and (2) & {3}, [4]. 100% a test 1; 2` 3; 5.          and 10 spaces."
5. Click on Submit
6. Click on Save & View

Expected results: The document selected is shown in the wiki page.

Actual results: Because of the comma `,` the title of the attachment is separated in 2 separate tabs which results in an error "Error: The document [xwiki:View Files macro.Te$t with #special + ch] does not exists or you have no access to that document." The file isn't shown.

![ViewFilesMacro](https://github.com/xwikisas/xwiki-pro-macros/assets/40691112/b2a56532-6091-406e-b9a9-63f213dd3f15)

Environment: Windows 11, XWiki 14.10.10 with MySQL 8.0, Chrome 114, Pro Macros 1.9

**Comment by ClemensRobbenhaar** [comment]
Side note: also appears without office server when using an PDF for me. The actual issue is that the `office` and `pdfviewer` macros use the comma as separator to show several files. This comma needs to be e.g. escaped if part of a file name.

**Comment by snazare** [comment]
to check if pdf viewer supports escaping and if so, escape the comma in the file name given to the view file macro.

**Comment by oanalavinia** [comment]
I reproduced this bug only for PDF files.
The PDFViewer issue was fixed as part of the [2.5.2](https://github.com/xwikisas/macro-pdfviewer/milestone/18?closed=1) release and the dependency was upgraded in https://github.com/xwikisas/xwiki-pro-macros/commit/01e2b2d10f16ea394d1e2252942dfa0a07c9c5a9
