### ISSUE TITLE
The "Show more" button of the Recently Updated macro does nothing after editing

### ISSUE THREAD

**Issue by ane-gabriela** [xwikisas/xwiki-pro-macros#143]
Steps to reproduce:

1. Edit a page
2. Click on Insert > Other macros
3. Search and select Recently Updated
4. Select a smaller Max ex. 5 (maximum number of results to be displayed)
5. Submit
6. Save & View
7. Click on "Show more"
![ShowMore](https://github.com/xwikisas/xwiki-pro-macros/assets/40691112/0fd8a9b0-ca7b-4b1f-b5b4-db014f912063)

Expected results: The other results appear.

Actual results: Nothing happens when clicking the "Show more" option.

**NOTE:** Once the page is refreshed the "Show more" option is functional and the results appear.

Environment: Windows 11, XWiki 14.10.10 with MySQL 8.0 and Chrome 114, Pro Macros 1.9

**Comment by mflorea** [comment]
The click listener for the Show More button needs to be registered also when the ``xwiki:dom:updated`` event is triggered (which happens when the in-place editor saves the content, without reloading the page).
