### ISSUE TITLE
UserList macro fires a NullPointerException due to conflict on WikiDescriptorManager field

### ISSUE THREAD

**Issue by slauriere** [xwikisas/xwiki-pro-macros#160]
## Steps to reproduce

In a wiki page, insert the userList macro as follows:

```
{{userList properties="avatar,username,email,company,phone" users="XWiki.JohnDoe,XWiki.MaryJohn" fixedTableLayout="true"/}}
```

## Expected result

The macro displays a table with the list of passed users.

## Actual result

Exception:

```
java.lang.NullPointerException
 at com.xwiki.macros.AbstractProMacro.execute(AbstractProMacro.java:113)
 at org.xwiki.rendering.internal.transformation.macro.MacroTransformation.transform(MacroTransformation.java:309)
 at org.xwiki.rendering.internal.transformation.DefaultRenderingContext.transformInContext(DefaultRenderingContext.java:183)
```

See full stack trace: 
[exception.txt](https://github.com/xwikisas/xwiki-pro-macros/files/12476974/exception.txt)

**Comment by slauriere** [comment]
Adding excerpts from the discussion on the `#product` chat:
* It is due to AbstractProMacro and UserListMacro declaring a field named wikiDescriptorManager which confuses the ComponentManager (as confirmed by Thomas, this is not supported)
* Anca points out that there is way too much private stuffs without getters in the abstract pro macro class for an abstract class
* I asked whether we should rename the field in the inherited class to something different. Thomas replied it could be exposed as a protected field instead, and that it all depends if we want to expose that field as an API or not.
* Anca points that the fix would be to either make getters to those fields or to make it a protected field, or, if you don't want it to be API, look it up dynamically in the abstract pro macro function that needs it and use it then (scope it to the function that absolutely needs it, as a need of the function and not as a need of the class and superclasses)

**Comment by slauriere** [comment]
I introduced a getter for field `wikiDescriptorManager` in `AbstractProMacro` and updated `UserListMacro` to use that getter instead of declaring the same field locally. This updated version works successfully on my side with XWiki 15.6 (while I was able to reproduce the NullPointerException beforehand).

ccing @raphj since it seems the issue was introduced in c845afce1

**Comment by slauriere** [comment]
Also ccing @snazare just in case :-)

**Comment by snazare** [comment]
thank you very much! We will plan a release soon :)
