### ISSUE TITLE
Support space separator in the recently updated macro's space parameter

### ISSUE THREAD

**Issue by raphj** [xwikisas/xwiki-pro-macros#167]
Note: it might affect other macros as well.

The Confluence recently-updated macro (and its XWiki counterpart) allow specifiying a list of spaces to consider.  This list of space can be comma-separated. This works on both implementation.

Confluence also allow spaces to be space-separated. This is an issue in XWiki, as spaces can contain spaces in their names.

It's not clear how we should support this.
 - with a parameter, disabled by default. It allows supporting the Confluence syntax, but users will have to manually add the parameters after migrations.
 - with a parameter, enabled by default . It allows supporting the Confluence syntax, it will work for Confluence users out of the box (to be verified), but will break for someone using the macro from XWiki and who has spaces in their space names.
 - another way?

Maybe the confluence migrator could add a parameter in the recently used macro so the parameter is set in a specific way when coming from a migration?

**Comment by aubincleme** [comment]
> Maybe the confluence migrator could add a parameter in the recently used macro so the parameter is set in a specific way when coming from a migration?

To be confirmed, but AFAIK it is possible through the implementation of Macro Converters : https://github.com/xwiki-contrib/confluence/blob/master/confluence-xml/src/main/java/org/xwiki/contrib/confluence/filter/MacroConverter.java

This is what's used to convert some macros we use in the Task Manager application for example : https://github.com/xwikisas/application-task/blob/master/application-task-default/src/main/java/com/xwiki/task/internal/DateMacroConverter.java
