### ISSUE TITLE
Support custom background color in the note macro and related macros

### ISSUE THREAD

**Issue by raphj** [xwikisas/xwiki-pro-macros#169]
Confluence lets users select a custom background color. Maybe we should support keeping this.

**Comment by snazare** [comment]
Hi @raphj we do support custom bg colours in the Panel macro; it usually looks something like: 

```
{{panel bgColor="#FFFAE6"}}
The content of the panel here
{{/panel}} 
```

Could you please clarify if this ticket would be for the Note macro specifically?
