### ISSUE TITLE
Unused att--filename parameter in Layout cell macro

### ISSUE THREAD

**Issue by petrenkonikita112263** [xwikisas/xwiki-pro-macros#174]
**Prerequisites**:

- XWiki instance 13.10
- Latest version of Pro Macros
- Trial license
- Having at least one attachment (any type) on a test page

**Step to reproduce**:

1. Go into Test Page, start editing it via Wiki mode. 
2. Copy/paste this line of code. Don't forget to replace filename with the existing one on your page.
```
{{layout-cell att--filename="image.jpg"}}
Lorem Ipsum is simply dummy text of the printing and typesetting industry.
{{/layout-cell}}
```
3. Save it.

**Actual result**
Despite of specified attachment, only text in a cell will be visible.
![image](https://github.com/xwikisas/xwiki-pro-macros/assets/56109799/25ffca6a-6d92-4758-b053-191d180f654f)

**Expected result**
I see that field att--filename was introduced in commit 5ef0116 in LayoutCell.xml file. I don't know what was the intention of it to display image/player/viewer in a cell, but if it has no effect, it can be removed other macros of Layout don't use it. That's why only content of macro shall be as input for this macro

**Comment by petrenkonikita112263** [comment]
From my last paragraph, instead of looking at this as bug, it can be a slight improvement by removing valueless field "att--filename" with further renaming the title of this issue.

**Comment by snazare** [comment]
att--filename is used by old versions of Confluence server.
