### ISSUE TITLE
Excerpt-include macro does not display images from excerpt

### ISSUE THREAD

**Issue by ClemensRobbenhaar** [xwikisas/xwiki-pro-macros#190]
I.e if an excerpt contains an image:
![page_with_excerpt](https://github.com/xwikisas/xwiki-pro-macros/assets/4411046/8f0fe11b-46bc-44fc-987d-7d48211a08ae)

then this is displayed as:

![page_with_excerpt-include](https://github.com/xwikisas/xwiki-pro-macros/assets/4411046/988b1558-9280-4e43-a2a5-f3e8d95fbbe2)

as the current implementation uses "include"-style instead of "display"-style rendering.

I would also prefer if the macro is written in Java and registers its `0` parameter (the included page) as a reference, so renaming the referenced page should update that parameter.

**Comment by acotiuga** [comment]
Hello @raphj! Please see the new PR https://github.com/xwikisas/xwiki-pro-macros/pull/210. 
The changes are 
`@since 1.14.4` -> `@since 1.14.5`
and 
```
TableBlock tableBlock = new TableBlock(List.of(
    new TableRowBlock(List.of(new TableHeadCellBlock(List.of(new WordBlock(document.getTitle()))))),
        new TableRowBlock(List.of(new TableCellBlock(Collections.singletonList(displayContent))))));

return List.of(tableBlock);
```
-> 
```
TableBlock tableBlock = new TableBlock(Arrays.asList(
    new TableRowBlock(
        Collections.singletonList(new TableHeadCellBlock(
            Collections.singletonList(new WordBlock(document.getTitle()))))),
    new TableRowBlock(
        Collections.singletonList(new TableCellBlock(
            Collections.singletonList(displayContent))))));

 return Collections.singletonList(tableBlock);
```
Second one ensure the successful build with Java 8.
Thanks for merging it and closing this issue and #192
