### ISSUE TITLE
Impossible to modify layout macros in the WYSIWYG editor

### ISSUE THREAD

**Issue by michitux** [xwikisas/xwiki-pro-macros#229]
Consider the following page source that has been migrated from Confluence:

```
{{layout}}
{{layout-section ac:type="single"}}
{{layout-cell}}
 Welcome to Confluence!
{{/layout-cell}}
{{/layout-section}}

{{layout-section ac:type="three_equal"}}
{{layout-cell}}
 {{children all="true"/}}
{{/layout-cell}}

{{layout-cell}}
 
{{/layout-cell}}

{{layout-cell}}
 
{{/layout-cell}}
{{/layout-section}}
{{/layout}}

{{layout}}
{{layout-section ac:type="single"}}
{{layout-cell}}
 

 
{{/layout-cell}}
{{/layout-section}}

{{layout-section ac:type="three_equal"}}
{{layout-cell}}
 
{{/layout-cell}}

{{layout-cell}}
 
{{/layout-cell}}

{{layout-cell}}
 
{{/layout-cell}}
{{/layout-section}}
{{/layout}}
```

It is impossible to edit this structure in the WYSIWYG editor as each macro is displayed just as one or two empty yellow boxes and there is no way to see where the actual content could/should be edited or how to change the structure:

![image](https://github.com/xwikisas/xwiki-pro-macros/assets/198317/a6fbf8f7-bc8e-4ccc-9f72-7f9e89a1c016)

In general, this construct of three nested macros is very hard to edit in the WYSIWYG editor even when the cells aren't empty. I would suggest adding some markers, e.g., using CSS, in edit mode to show which box is which and to make it easier to see where the content should be edited.

**Comment by snazare** [comment]
closing as not planned as the layout macro, along with section and column are bridge macros, to be used only to display data imported from Confluence. We should implement a new functionality in order to address this usecase.  relates to #242
