### ISSUE TITLE
Support calendar macro as part of a migration process

### ISSUE THREAD

**Issue by AndreeaChi** [xwikisas/xwiki-pro-macros#234]
Currently, in the [documentation](https://store.xwiki.com/xwiki/bin/view/Extension/Confluence%20Migrator%20Application%20%28Pro%29/#documentation) > [Supported confluence macros](https://store.xwiki.com/xwiki/bin/view/Extension/Confluence%20Migrator%20Application%20%28Pro%29/#HSupportedconfluencemacros) there is a mention that the calendar macro is not "Migration supported":

> calendar | No | Configurable calendar macro. Date macro exists.

**Comment by snazare** [comment]
we will create a sub module xwiki-pro-macros-macro-date on which pro macros and task manager will depend on. Currently the date macro is implemented in the task manager and you need the Task Manager Pro app installed so that it works.
