### ISSUE TITLE
Improve display of view-file macro

### ISSUE THREAD

**Issue by snazare** [xwikisas/xwiki-pro-macros#239]
Currently the view-file macro converts view-doc and view-xls into the XWiki native {{office}} macro, which displays the full content of the office document in the page. 

Suggested improvements: 
1. implement a thumbnail view parameter, that will display the document in a small box. 
2. implement a scrollable contained view, similar to the Pro pdf viewer macro. 

Editing: 
- replace reference field with a selector.

**Comment by ChiuchiuSorin** [comment]
I have a couple of questions regarding this issue: 
1. For 

> implement a scrollable contained view, similar to the Pro pdf viewer macro

Is the intention to create a viewing window similar to that of the `PDF viewer` for any document loaded into the macro, regardless of extension? If so, should it also have the size customization of the `PDF viewer macro`?
2. Regarding 

> implement a thumbnail view parameter, that will display the document in a small box

It's not very clear to me how it should look, what the dimensions should be, and in what situation it would apply.
3. 

> Replace reference field with a selector

 I assume this refers to the way the file to be displayed is selected?

**Comment by snazare** [comment]
Hi @ChiuchiuSorin  thank you for your questions. 

> Is the intention to create a viewing window similar to that of the PDF viewer for any document loaded into the macro, regardless of extension? If so, should it also have the size customization of the PDF viewer macro?

Upon further investigation I noted that Confluence has 

1. `view-file` macro which shows documents in a thumbnail of 125 * 156 px (this is the one we currently bridge to our office macro, which puts the whole content of the doc in the page)
2. `viewfile` macro which shows documents in an embeded scrollable window, like our PDF viewer. 

To keep support for both, I would propose as follows: 
1. improve the office macro to show the file in an embeded frame, like the PDF viewer
2. add parameter `display` to the improved macro, with the following options: 
* thumbnail - displays the file in a thumbnail
* full - displays the file in an embeded scrollable window

3. map the `view-file` macro to {{office display="thumbnail" filename="..." /}}
map the `viewfile` macro to {{office display="full" filename="..." /}}

If we go this route, is there a way to still be able to customize the size of the window if display="full" is chosen? 

> I assume this refers to how to select a file to be displayed?

Yes, in the macro editor we should allow the user to select the page and the attachment with a selector, not a reference field. 

WDYT? Do you agree with this direction?

**Comment by snazare** [comment]
one more note, if the height parameter is set on the current view-file macro, the height value is not applied on the PDF viewer macro instead the default height value (1000) is applied.

**Comment by snazare** [comment]
following more discussions: 

1. we improve the existing view-file macro to display documents in a box 
2. add a parameter for display (`thumbnail` or `full`)
2.1 to support `view-file` (thumbnail view) we display a thumbnail image in a box in view mode and when you click on the image you see the document in full screen in a modal
2.2 to support `viewfile` (full view) we display the file in a scrollable box within the page
3. when using the full view mode, we support parameters width and height
4. when importing:
4.1 map the view-file macro to {{view-file display="thumbnail" filename="..." /}}
4.2 map the viewfile macro to {{view-file display="full" filename="..." /}}
