### ISSUE TITLE
Expand macro content is not displayed in a PDF export

### ISSUE THREAD

**Issue by lamblinc** [xwikisas/xwiki-pro-macros#246]
Content of an expand macro should be visible in a PDF export.

**Comment by snazare** [comment]
I reproduce the issue on xwiki 15.10.10 Chrome 

`https://confluencemigration.demo.xwiki.com/xwiki/bin/get/Sandbox/?outputSyntax=plain&sheet=XWiki.PDFExport.WebHome&data=jobStatus&jobId=export%2Fpdf%2F1720441145082-102
`
