### ISSUE TITLE
Column macros with width 50 are hard to edit in CKEditor

### ISSUE THREAD

**Issue by petrenkonikita112263** [xwikisas/xwiki-pro-macros#247]
**Prerequisites**:

- XWiki instance 13.10+
- Latest version of Pro Macros
- Trial license

**Step to reproduce**:

1. Navigate into any test page on Sandbox space and put the below source code in Wiki mode editing
```
{{section border="true"}}

{{column width="50"}}
column1
{{/column}}

{{column width="50"}}
column2
{{/column}}

{{/section}}
```
2. Trigger editing mode via CKEditor or WYSIWYG editor

**Actual result**
![image](https://github.com/xwikisas/xwiki-pro-macros/assets/56109799/7df0fe30-7f7b-4bd1-8914-17760240a118)
2nd column overlaps the 1st column, making it hard to edit its content. Only the user can jump from the start to end line via a shortcut (in case Windows OS CTRL + → or CTRL + ←).

**Expected result**
There's no overlapping during edit mode, unlike during view mode.

![image](https://github.com/xwikisas/xwiki-pro-macros/assets/56109799/05e436f2-e8f2-4b86-a4b9-32b7c1ad32cb)

**Comment by snazare** [comment]
closing this as column and section are bridge macros, only to be used in the context of a migration to display data from Confluence. They should not be used post migration as standalone macros. We should implement a new functionality in order to address this usecase.
