### ISSUE TITLE
Make it clear in all macro names which macros are Confluence bridges

### ISSUE THREAD

**Issue by michitux** [xwikisas/xwiki-pro-macros#252]
There should be a unified way how macros are marked that are Confluence bridge macros. At the moment, there is a mix, some macros have no information at all, some have it in the description, some like "Confluence Gallery" have it in the name:

![image](https://github.com/xwikisas/xwiki-pro-macros/assets/198317/9ea6f3ac-468b-4951-a72f-4be93b7aa9ab)

![image](https://github.com/xwikisas/xwiki-pro-macros/assets/198317/f7c6d79f-ace4-4f9f-940a-f355747b5c98)

![image](https://github.com/xwikisas/xwiki-pro-macros/assets/198317/adb2cfcc-0b2f-46c9-be17-4f55c92dddaa)

**Comment by trrenty** [comment]
The issue was mostly solved by #277 . Some macro names and descriptions were overwritten by the translation files.
