### ISSUE TITLE
Pro Macros license not seen as valid after an upgrade to version 1.19.0

### ISSUE THREAD

**Issue by raphj** [xwikisas/xwiki-pro-macros#286]
This is caused by https://github.com/xwikisas/application-licensing/issues/174

This ticket is for working around the issue, a proper fix will be provided later.

**Comment by oanalavinia** [comment]
This workaround was removed as part of the upgrade to licensing 1.29 https://github.com/xwikisas/xwiki-pro-macros/issues/532
