### ISSUE TITLE
The expand macro generates invalid HTML

### ISSUE THREAD

**Issue by oanat** [xwikisas/xwiki-pro-macros#295]
To be precise, it generates a DIV inside the summary element:
```
<details>
  <summary>
    <span class="panel-title">Title</span>
  </summary>
  <div class="panel-body">Body</div>
</details>
```
According to Marius the specification of the summary element says https://developer.mozilla.org/en-US/docs/Web/HTML/Element/summary

> The <summary> element's contents can be any heading content, plain text, or HTML that can be used within a paragraph.
> ...
> Permitted content: Phrasing content or one element of Heading content
> 

So DIV inside the summary element is not allowed. Replacing the DIV with a SPAN should fix the problem.

**Comment by lucaa** [comment]
@Farcasut @trrenty shouldn't this ticket also have a milestone, now that it's closed? To know in what version to expect it fixed?
