### ISSUE TITLE
Convert profile macro into userProfile at import time

### ISSUE THREAD

**Issue by snazare** [xwikisas/xwiki-pro-macros#314]
We have a userProfile generic macro that has the same functionality as Confluence's profile macro https://confluence.atlassian.com/doc/user-profile-macro-189432828.html

Please convert `profile` into `userProfile` upon import and convert parameter `user` (from profile macro) to parameter `reference` (from userProfile macro).

**Comment by trrenty** [comment]
This was done as part of confluence migrator. See https://github.com/xwikisas/application-confluence-migrator-pro/issues/152 . Does the conversion not work?

**Comment by snazare** [comment]
Hi @trrenty you're right, my bad. Closing the ticket
