### ISSUE TITLE
Convert "userlister" into "userList" macro

### ISSUE THREAD

**Issue by snazare** [xwikisas/xwiki-pro-macros#317]
'userlister" is a more basic bridge macro, while userList is a generic macro with more parameters.

**Comment by snazare** [comment]
we also need to move userlister to legacy macros module and recommend userList as a generic macro, in the generic module

**Comment by trrenty** [comment]
The moving of the macro was done by this commit https://github.com/xwikisas/xwiki-pro-macros/commit/55bb33cd3d6e8aef56f7007d111e80ff9ecbcd3d
