### ISSUE TITLE
Panel macro - Content text isn't fully showing when setting Height in px

### ISSUE THREAD

**Issue by ane-gabriela** [xwikisas/xwiki-pro-macros#33]
Steps to reproduce:

1. Edit a page
2. Click on Insert > Other Macros
3. Search and select Panel Macro
4. Under Content section add a large amount of text
5. Click on Submit > Save & View  ![FullView](https://user-images.githubusercontent.com/40691112/112333824-98807980-8cc3-11eb-8aaa-68bb251cc38c.png)
7. Edit the macro and add a small Height eg. 300px or smaller

Expected results: A scrollbar is added when the text is longer then the Height set, so that the user can see the full content.

Actual results: The text is cut, no scrollbar appears. 

![CutTExt](https://user-images.githubusercontent.com/40691112/112334257-f44b0280-8cc3-11eb-9e42-aadb78e38c3d.png)

**NOTE**: In Edit more the Up/Down arrows work to show the text in the Content but not in View mode.
If the browser screen is narrowed more text disappears.

Environment: Windows 10, IE 11, XWiki 12.10.4 with MySQL 8.0 and xwiki-pro-macros 1.0-RC1

**Comment by acotiuga** [comment]
The height parameter was wrongly added from the beginning. It doesn't make sense to limit the content size using the height limitation, as the content will be truncated
