### ISSUE TITLE
Status macro - Can't add 2 status macros one after another

### ISSUE THREAD

**Issue by ane-gabriela** [xwikisas/xwiki-pro-macros#34]
Steps to reproduce:

1. Edit a page
2. Click on Insert > Other Macros
3. Search and select Status Macro
4. Add a Title, choose a Color eg. Blue and Submit
5. Click on the red arrow below the added macro to add a new line "Insert paragraph here" 
![InsertParagraph](https://user-images.githubusercontent.com/40691112/112486623-b95cd380-8d84-11eb-9b7b-6d579126fd0b.png)
6. Click on Insert > Other Macros
7. Search and select Status Macro
8. Add a Title, choose a Color eg. green and Submit 
![2TasksInEditMode](https://user-images.githubusercontent.com/40691112/112487339-50299000-8d85-11eb-9987-1a548394c660.png)
9. Click on Save & View

Expected results: The status macros selected are saved.

Actual results: The second macro is added and seen in Edit mode, after clicking on Save & View the second status macro disappears (in View mode). 
![ViewMode](https://user-images.githubusercontent.com/40691112/112487829-b6161780-8d85-11eb-923e-1a2e86a378c9.png)

In Source Mode 
![SourceMode](https://user-images.githubusercontent.com/40691112/112487973-d5ad4000-8d85-11eb-8118-2bcd70d2037b.png)

**NOTE:**
I've also tried to add 3-4 tasks one after another. 
In Edit mode:
- the first status macro remains
- the second macro is replaced each time by the new macros added
In View mode:
- only the first status macro is shown

Environment: Windows 10, IE 11, XWiki 12.10.4 with MySQL 8.0 and xwiki-pro-macros 1.0-RC1

**Comment by acotiuga** [comment]
With clean=false
![htmlCleanFalse](https://user-images.githubusercontent.com/8121819/116451218-e3faea00-a864-11eb-8ee2-1c48c58a0282.png)

Without clean=false
![html](https://user-images.githubusercontent.com/8121819/116451244-ea896180-a864-11eb-95b2-3da7ed00d009.png)
