### ISSUE TITLE
Gliffy Macro - Diagram page is created as a sibling to the Gliffy page

### ISSUE THREAD

**Issue by ane-gabriela** [xwikisas/xwiki-pro-macros#36]
When imported in a XWiki page the Gliffy page is created as a Terminal page thus when Converting to an editable page, Diagram is created as a sibling instead of a child.

I believe this is also the reason for #35 

![Siblings](https://user-images.githubusercontent.com/40691112/112669136-02d21f00-8e68-11eb-8281-b525990505b0.png)

Environment: Windows 10, IE 11, XWiki 12.10.4 with MySQL 8.0 and xwiki-pro-macros 1.0-RC1

**Comment by ndascalita** [comment]
Could not replicate with Pro Macros 1.14.1 on XWiki 14.10.16

**Comment by snazare** [comment]
not reproducing on XWIki 15.10.10, Pro Macros 1.19.6
