### ISSUE TITLE
detailssummary doesn't show lists contained in listed pages in the table

### ISSUE THREAD

**Issue by raphj** [xwikisas/xwiki-pro-macros#362]
Some users have lists in pages that are then shown in a confluence_detailssumary macro. The content is empty, instead of showing the lists/bullets. We should show lists.

**Comment by snazare** [comment]
Hi @raphj I tried to reproduce the issue but I am not sure I understand. Could you please provide a screenshot demonstrating the issue and steps to reproduce? 

I tested on XWiki 15.10, local instance

<img width="1679" alt="issue-detailssummary1" src="https://github.com/user-attachments/assets/89c0c96f-0304-460f-b7b3-504dde597a8d">
<img width="1680" alt="issue-detailssummary2" src="https://github.com/user-attachments/assets/11729753-3fa5-4402-be8d-186d96af9374">
