### ISSUE TITLE
Content Report Table Macro - Content field appears in the macro but isn't mentioned in the Parameters

### ISSUE THREAD

**Issue by ane-gabriela** [xwikisas/xwiki-pro-macros#44]
The Content field appears in the macro, but this is not detailed in the Parameters in the documentation page https://confluence-migrator.devxwiki.com/xwiki/bin/view/Confluence/Macros/ContentReportTableMacro

What should be the purpose of this field?

![Documentation](https://user-images.githubusercontent.com/40691112/113437942-4096f080-93f0-11eb-99fa-75314657c2eb.png)

Environment: Windows 10, IE 11, XWiki 12.10.4 with MySQL 8.0 and xwiki-pro-macros 1.0-RC1

**Comment by acotiuga** [comment]
This macro should not expect content as input from users.
