### ISSUE TITLE
Section Macro - Content field appears in the macro but isn't mentioned in the Parameters

### ISSUE THREAD

**Issue by ane-gabriela** [xwikisas/xwiki-pro-macros#49]
The Content field appears in the macro, but this is not detailed in the Parameters in the documentation page https://confluence-migrator.devxwiki.com/xwiki/bin/view/Confluence/Macros/Section

What should be the purpose of this field?

![Section Content](https://user-images.githubusercontent.com/40691112/113579724-5e04ce00-962d-11eb-8792-1ce347aff75b.png)

Environment: Windows 10, IE 11, XWiki 12.10.4 with MySQL 8.0 and xwiki-pro-macros 1.0-RC1

**Comment by acotiuga** [comment]
There are macro parameters and macro content. The parameters are used for content manipulation and the content is simply the text/information the user adds in the macro. At least the fact that the content is not a parameter is a reason to not list it in the parameters table
