### ISSUE TITLE
Column Macro - Content field appears in the macro but isn't mentioned in the Parameters

### ISSUE THREAD

**Issue by ane-gabriela** [xwikisas/xwiki-pro-macros#50]
The Content field appears in the macro, but this is not detailed in the Parameters in the documentation page https://confluence-migrator.devxwiki.com/xwiki/bin/view/Confluence/Macros/Column

What should be the purpose of this field?

![Column Content](https://user-images.githubusercontent.com/40691112/113582302-dfaa2b00-9630-11eb-84cc-28091df01d69.png)

Environment: Windows 10, IE 11, XWiki 12.10.4 with MySQL 8.0 and xwiki-pro-macros 1.0-RC1

**Comment by acotiuga** [comment]
See https://github.com/xwikisas/xwiki-pro-macros/issues/49#issuecomment-824694862
