### ISSUE TITLE
Content Report Table Macro - The page that is added in the Space section isn't shown in the report although it has the selected label

### ISSUE THREAD

**Issue by ane-gabriela** [xwikisas/xwiki-pro-macros#52]
It appears that the pages that are considered the "Space(s) to report on" don't appear in the Content Report Table even if they have the selected label.

Report:
![SpaceAndLabel](https://user-images.githubusercontent.com/40691112/113631822-b5795d00-9672-11eb-950a-383109c6e2a7.png)

Pages shown:
![Result](https://user-images.githubusercontent.com/40691112/113631833-b90ce400-9672-11eb-94da-3547d24f7367.png)

Missing page:
![StatusSpace](https://user-images.githubusercontent.com/40691112/113631843-bc07d480-9672-11eb-8451-0ae16dcc02c3.png)

Environment: Windows 10, IE 11, XWiki 12.10.4 with MySQL 8.0 and xwiki-pro-macros 1.0-RC1

**Comment by acotiuga** [comment]
Fixed in https://github.com/xwikisas/xwiki-pro-macros/commit/d1f425469dc9c99e7b425c1940be4ad55739fc7b.
