### ISSUE TITLE
Do not bundle the diagram app in the pro macro package

### ISSUE THREAD

**Issue by ldubost** [xwikisas/xwiki-pro-macros#58]
I think we would need to not automatically bundle the diagram package in the pro macro package.
We should however detect in the gliffy wrapper if the app is there and suggest installation

Otherwise this makes a big dependency even when you don't need gliffy

**Comment by acotiuga** [comment]
Result:
![diagramMissingWarningMessage](https://user-images.githubusercontent.com/8121819/127295512-c53ac586-68f5-4ff9-8861-466d20c4e82c.png)
