### ISSUE TITLE
view-file macro not working inline

### ISSUE THREAD

**Issue by ldubost** [xwikisas/xwiki-pro-macros#59]
When using the following content seen from a Confluence export

{{view-file att--filename="Note sur la modification du ROI.docx" name="" height="250"/}} Modification ROI (note rédigée par Olenka)

The following error show up

The [view-file] macro is a standalone macro and it cannot be used inline Modification ROI (note rédigée par Olenka)

Apparently confluence import can have inline macros in some cases. We would need avoid the error

**Comment by ClemensRobbenhaar** [comment]
Indeed I have seen the same problem with the `viewpdf` macro with some migration data, but unfortunately I have been unable to get the original Confluence data from the users.

**Comment by mflorea** [comment]
```
{{view-file att--filename="Note sur la modification du ROI.docx" name="" height="250"/}} Modification ROI (note rédigée par Olenka)
```

@ldubost this is the generated wiki syntax after the Confluence import / migration. Would be nice to also have the actual Confluence XML/HTML content that generated this (to see if this is something we can fix in the Confluence filter stream) and to know how this was displayed by Confluence. Was the "Modification ROI" text displayed inline on the right of the file in Confluence?

**Comment by snazare** [comment]
closing as inactive/duplicate of #157 . We will need an example file to reproduce and fix the issue.
