### ISSUE TITLE
Create a button macro

### ISSUE THREAD

**Issue by silviamacovei** [xwikisas/xwiki-pro-macros#64]
It would be nice to be able to add noticeable clickable buttons on XWiki pages to highlight links and create call to actions.
The macro should allow users to configure the:
* Label
* URL: link or page reference
* Color
* Width - If no width is set, it will be determined by the text length
* The possibility to open in new tab

**Comment by trrenty** [comment]
Created the button macro. As discussed with @silviamacovei , I also added a `icon` parameter. The following image displays different usages of the macro.
![image](https://user-images.githubusercontent.com/45433221/162190839-6a9a931b-c2ed-4532-b048-9ce23a394f06.png)
The URL parameter uses a [page picker](https://www.xwiki.org/xwiki/bin/view/ReleaseNotes/Data/XWiki/10.9/Change011/), the color parameter uses a [color picker](https://www.xwiki.org/xwiki/bin/view/Documentation/DevGuide/FrontendResources/Pickers#HColorPicker) and the icon parameter uses a [icon picker](https://www.xwiki.org/xwiki/bin/view/IconThemesCode/IconPickerMacro).
![image](https://user-images.githubusercontent.com/45433221/162192477-4ffd52a0-397c-40dd-b9ab-42e584d7fb69.png)
The button is stylized the following way: The background has the color chosen by the user, the borders are a darker version of the aforementioned color and the text color is either black or white, depending which one has the better contrast.

WDYT?

**Comment by silviamacovei** [comment]
Looks really good to me @trrenty ! Looking forward to test and use it :)
