### ISSUE TITLE
Note, info, tip, warning, error macros should show an icon

### ISSUE THREAD

**Issue by ClemensRobbenhaar** [xwikisas/xwiki-pro-macros#72]
No, really, people are missing them. `^^`

**Comment by snazare** [comment]
current mapping: 
<img width="1353" alt="Screenshot 2022-10-27 at 01 20 40" src="https://user-images.githubusercontent.com/35834028/198149573-d94eaec0-3606-4ac3-9bee-6c7e6e9a5dea.png">

**Comment by snazare** [comment]
will be tacked in #97
