### ISSUE TITLE
Create the "recently-updated" macro

### ISSUE THREAD

**Issue by snazare** [xwikisas/xwiki-pro-macros#84]
Please create the "recently-updated" macro, compatible with the Confluence macro: https://confluence.atlassian.com/doc/recently-updated-macro-139519.html

**Parameters priority 1:**

Parameter | Default | Description
-- | -- | --
Author(s) by username(author) | None specified. That is, display all content | Filter the results by author. The macro will display only the pages etc which were last modified by the author(s) you specify here.You can specify multiple users.
Space(s)(spaces) | @selfThat is, the space which contains the page on which the macro is used | This parameter allows you to filter content by space. The macro will display only the pages etc which belong to the space(s) you specify here.You can specify one or more space keys, separated by a comma or a space. To exclude content in a specific space, put a minus sign (-) immediately in front of that space key. For example: If you specify a space key of -BADSPACE you will get only content that is not in the BADSPACE.To indicate that the results must come from a specific space, put a plus sign (+) immediately in front of that space key. For example: If you specify a space key of +GOODSPACE you will get only content in GOODSPACE. (Note that this is not particularly useful, because each content item belongs to one space only. If you put a plus sign next to one space key and list other space keys too, the other space keys will be ignored.)Special values:@self — The current space.@personal — All personal spaces.@global — All site spaces.@favorite — The spaces you have marked as favorite.@favourite — The same as @favorite above.@all — All spaces in your Confluence site.* — The same as @all above.When specifying a personal space, remember to use the tilde (~) sign in front of the username, such as ~jbloggs or ~jbloggs@example.com.
Label(s)(labels) | None specified i.e. display all content | Filter the results by label. The macro will display only the pages etc which are tagged with the label(s) you specify here.You can specify one or more label values, separated by a comma or a space.To exclude content which matches a given label, put a minus sign (-) immediately in front of that label value. For example: If you specify a label value of -badpage you will get only content which is not labeled with 'badpage'.To indicate that the results must match a given label value, put a plus sign (+) immediately in front of that label value. For example: If you specify a label value of +superpage,+goodpage you will get only content which has at least two labels, being 'superpage' and 'goodpage'.The labels parameter only applies to the page and blog content types.
Maximum Number of Results(max) | 15 | Specify the maximum number of results to be displayed. If this parameter is omitted, then a maximum of 15 results are displayed. The theoretical maximum value that this parameter can accept is 2 to the power of 31, minus 1 (or 2147483647), though this has been limited to 200 in the code, for performance reasons. More details are here.

**Parameters priority 2:**

Parameter | Default | Description
-- | -- | --
Width of Table(width) | 100% | Specify the width of the macro display, as a percentage of the window width.
Include these Content Types Only(types) | All types | This parameter allows you to filter content by content type. The macro will display only the content of the type you specify here.You can specify one or more types, separated by a comma or a space.To exclude content of a given content type, put a minus sign (-) immediately in front of that content type. For example: If you specify a content type of -blogpost you will get pages and all other content except for blog posts.Available values:page — Pages.blogpost or news — Blog posts, also known as news items.comment — Comments on pages and blog posts.attachment — Attachments.
theme(theme) | concise | Choose the appearance of this macro:concise — the default list, showing the names of pages which were updated or commented on, the users who made the page modifications and time when the modifications occurred.social — lists recent modifications in reverse chronological order, but groups them by user into short time segments. A 'sub' list appears within each user's time segment, showing the names of pages which they updated or commented on and time when these modifications occurred.sidebar — lists recent updates in reverse chronological order, showing the names of pages which were updated or commented on and time when the page modifications occurred. This theme does not show authorship.
Show User Profile Pictures(showProfilePic) | false | Specify showProfilePic=true to display the profile pictures of the users who updated the content.
Hide Title(hideHeading) | False | Determines whether the macro hides or displays the text 'Recently Updated' as a title above the list of content. Only available in wikimarkup and storage format.Accepted values:true – Title is hidden.false – Title is shown.

**Comment by ClemDee** [comment]
Recenctly-updated macro bridge implemented.
