### ISSUE TITLE
Create the "Expand" bridge macro

### ISSUE THREAD

**Issue by snazare** [xwikisas/xwiki-pro-macros#85]
Please create the "Expand" bridge macro, compatible with the Confluence Expand macro: https://confluence.atlassian.com/doc/expand-macro-223222352.html

Please note that XWiki already has a similar macro: https://extensions.xwiki.org/xwiki/bin/view/Extension/Document%20Accordion%20Macro/

Parameters: 

Parameter | Default | Description
-- | -- | --
Title | Click here to expand... | Defines the text that appears next to the expand/collapse icon.

**Comment by ClemDee** [comment]
Expand macro bridge implemented.
