### ISSUE TITLE
Create the "userlister" macro

### ISSUE THREAD

**Issue by snazare** [xwikisas/xwiki-pro-macros#88]
Please create the "userlister" bridge macro, compatible with the Confluence userlister macro: https://confluence.atlassian.com/doc/user-list-macro-139546.html

Name: userlister 

Parameter | Default | Description
-- | -- | --
Group(s)(groups) | none | Specify the group name. Specify multiple groups separated by a comma, or use * to show all users in Confluence.See this knowledge base page for more information about controlling which users can see the details of other users.

**Comment by raphj** [comment]
I'm adding support for the groups parameter in the `userList` macro.
https://github.com/xwikisas/xwiki-pro-macros/pull/98

I don't know yet how groups are mapped from confluence to XWiki. I need to figure this out before I can implement the `userlister` confluence bridge macro.

**Comment by oanalavinia** [comment]
This has no commits on the main branch. @raphj should the [support-groups-in-userList](https://github.com/xwikisas/xwiki-pro-macros/compare/support-groups-in-userList) branch be merged? Or do you still have work to do and we could reopen the issue

**Comment by slauriere** [comment]
Work on PR #98 is still in progress so I'm reopening this issue.
