### ISSUE TITLE
User List macro: the list of users cannot be updated correctly

### ISSUE THREAD

**Issue by slauriere** [xwikisas/xwiki-pro-macros#89]
## Steps to reproduce

* In wysiwyg mode, select User List macro for insertion
* In the macro "users" parameter input, pick several users
* Insert macro
* Edit macro

## Actual result

The user picker in the macro edit dialog displays only the last user of the list instead of the complete list of picked users, while the users are correctly listed in wiki syntax mode.

**Comment by slauriere** [comment]
See [this comment](https://github.com/xwikisas/xwiki-pro-macros/pull/75#discussion_r983061705) by @mflorea for a possible fix.

**Comment by lucaa** [comment]
I don't really understand the suggested fix...

I noticed this same issue on XWiki 14.4.3.

**Comment by snazare** [comment]
can not reproduce on xwiki 15.10.10, pro macros 1.19.9
