### ISSUE TITLE
Team Macro: cannot use the macro on a subwiki to display users from the main wiki

### ISSUE THREAD

**Issue by lucaa** [xwikisas/xwiki-pro-macros#91]
When used on a subwiki, even if the wiki is configured to use global users, the team macro will display no results.

It would be a good feature to be able to display a team of users from the main wiki on a subwiki:
* either with a parameter to specify the scope of users to be displayed
* or by checking the users scope setting for the current wiki and switching between local and global users based on its value.

**Comment by raphj** [comment]
I added the `scope` parameter to the team macro. Default value: `auto`. Possible values:
 - `auto: depending on the wiki settings, will look up users in the global wiki, the local wiki or both
 - `both`: will look up users in both wikis
 - `local`: will look up users in the local wiki only 
 - `global`: will look up users in the global wiki only 

The parameter has no effect in the main wiki.

This implements both of your proposals @lucaa.
