### ISSUE TITLE
Team Macro: wrong links displayed for users

### ISSUE THREAD

**Issue by lucaa** [xwikisas/xwiki-pro-macros#92]
How to reproduce:
* add the label 'testuser' to a couple of users
* add the folllowing macro call in a page (default parameters except for tag):
`{{team tag="testuser" disableLetterAvatars="false"/}}`
* save and view the page

Expected result:
* when clicking on the user avatars that are displayed, it takes to the user page

Actual result:
* the link under the _first_ user avatar is a link to the current page which contains the macro call
* the link under the _second_ user avatar is a link to the _image_ that is the avatar of the first user avatar

**Comment by raphj** [comment]
Fixed. The issue was that the code was referring to an unset $url variable. Well, it was actually set by the macro generating the avatar picture.
