### ISSUE TITLE
Diagram is empty after conversion from drawio

### ISSUE THREAD

**Issue by snazare** [xwikisas/xwiki-pro-macros#99]
1. Import a page containing a drawio diagram from confluence
2. Find the imported page in XWiki 
3. Click on convert to diagram 

Expected result: the drawio diagram is converted into an XWiki diagram and can be edited

Actual result: the drawio diagram is converted, but the page is empty

https://user-images.githubusercontent.com/35834028/202404807-ecef4359-5c67-4427-96f7-b57de5ce0cb3.mp4

Environment: XWiki 14.4.6, cloud, Confluence Migrator 1.0.8, Pro Macros 1.6

**Comment by raphj** [comment]
For the record, it seems to be caused by the missing `.drawio` extension in the attachments. I copied this page, added the extensions and it worked. So something is not happy when  the `.drawio` extension is not there.

**Comment by raphj** [comment]
The drawio bridge macro does not require any .drawio extension anymore. Thanks @oanalavinia for the investigation.
